import image1 from "@/public/images/user/user-01.png";
import image2 from "@/public/images/user/user-02.png";
import { Testimonial } from "@/types/testimonial";

export const testimonialData: Testimonial[] = [
  {
    id: 1,
    name: "David S.",
    designation: "Founder @GrowthLabs",
    image: image2,
    content: "This platfrom is awesome! We automated our campains and now things run smooth. No more late nights doing boring work.",
  },
  {
    id: 2,
    name: "Sarah J.",
    designation: "Marketing Lead @NextGenTech",
    image: image2,
    content: "I luv how easy it is. The AI suggestions are actually good and our ROI is way better than before. Great job team!",
  },
  {
    id: 3,
    name: "Michael Chen",
    designation: "Ops Manager @FinEdge",
    image: image2,
    content: "Man, setting this up was quick. And it feels like we got an extra teammate working 24/7. Kinda crazy how much time we saved!",
  },
  {
    id: 4,
    name: "Priya P.",
    designation: "Co-Founder @BrandSphere",
    image: image2,
    content: "We used to juggle a lot of tools. Now its all in 1 place. Honestly, loving the automation. Wish I found it sooner.",
  },
  {
    id: 5,
    name: "Alex M.",
    designation: "CEO @SmartSolutions",
    image: image2,
    content: "Emails, social media posts, customer followups all automated. I literally just watch results now, lol.",
  },
  {
    id: 6,
    name: "Linda K.",
    designation: "Head of Growth @TechNova",
    image: image2,
    content: "Predictive analytics is mind blowing. Not sure how it works but it shows exactly what to do next, we are seeing engagement shoot up.",
  },
  {
    id: 7,
    name: "Robert L.",
    designation: "Product Manager @OptiFlow",
    image: image2,
    content: "Integrating was painless. AI keeps giving tips. Sometimes I forget it’s even running automatically, haha.",
  },
  {
    id: 8,
    name: "Nina G.",
    designation: "CEO @InnovateX",
    image: image2,
    content: "Feels like I got a growth partner. Tasks get done, insights are real, my team can breathe now. 10/10 would recommend.",
  },
  {
    id: 9,
    name: "Samuel R.",
    designation: "Owner @LocalBizCo",
    image: image2,
    content: "Small biz here, but this AI helps me reach customers I never could before. Automation is super simple to use.",
  },
  {
    id: 10,
    name: "Anita S.",
    designation: "Founder @MSMEBoost",
    image: image2,
    content: "I dont know tech much but this is user friendly. Literally did setup in 30 mins and my campaigns went live. Yay!",
  },
  {
    id: 11,
    name: "Tom H.",
    designation: "Marketing Head @RetailPro",
    image: image2,
    content: "We were sending emails manually, now AI handles everything. I drink coffee while it works, lol.",
  },
  {
    id: 12,
    name: "Rita K.",
    designation: "Co-Founder @EduSmart",
    image: image2,
    content: "The insights are legit helpful. I see which student segments react best to our messages. Wish we had this 2 years ago.",
  },
  {
    id: 13,
    name: "Vikram P.",
    designation: "Founder @TechSolutions",
    image: image2,
    content: "Scaling was tough, now AI handles workflow, data tracking, even followups. Feels like my biz just got wings.",
  },
  {
    id: 14,
    name: "Emily B.",
    designation: "CEO @ShopEase",
    image: image2,
    content: "Honestly, the automation is addictive. Once you see results, you can’t go back. Love how intuitive it is.",
  },
  {
    id: 15,
    name: "Rahul D.",
    designation: "Operations Lead @AutoTech",
    image: image2,
    content: "I sometimes mess up, but AI keeps track. Helps even my team avoid mistakes. Super helpful!",
  },
  {
    id: 16,
    name: "Sophia W.",
    designation: "Founder @Healthify",
    image: image2,
    content: "Automation + insights = time saved. My clinic runs better now, patients happier, team happier, me happier 😄",
  },
  {
    id: 17,
    name: "Carlos M.",
    designation: "CEO @LogiCorp",
    image: image2,
    content: "Big biz here, AI handles campaigns, analytics, even customer reach. Feels like a full dept working nonstop.",
  },
  {
    id: 18,
    name: "Fatima Z.",
    designation: "Owner @FashionLine",
    image: image2,
    content: "Silly me, I was sending DMs manually 😅. Now AI does it all. Our engagement doubled.",
  },
  {
    id: 19,
    name: "Daniel K.",
    designation: "Founder @FinTechies",
    image: image2,
    content: "I trust this AI more than interns 😆. Seriously, saves hours, accurate, and scaling my startup is easier.",
  },
  {
    id: 20,
    name: "Meera S.",
    designation: "CEO @BizGrow",
    image: image2,
    content: "Everything automated from reporting to campaign followups. Helps my team focus on strategy, not busywork.",
  },
];
